setono_sylius_terms_show:
    path: /terms/{slug}
    methods: [GET]
    defaults:
        _controller: setono_sylius_terms.controller.action.show_terms

setono_sylius_terms_partial_show:
    path: /terms/{slug}/partial
    methods: [GET]
    defaults:
        _controller: setono_sylius_terms.controller.terms::showAction
        _sylius:
            template: "@SetonoSyliusTermsPlugin/Shop/Terms/partialShow.html.twig"
            repository:
                method: findOneByChannelAndSlug
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - $slug
